# -*- coding: utf-8 -*-
"""Untitled2.ipynb

Automatically generated by Colab.

Original file is located at
    https://colab.research.google.com/drive/1JBQCtLZ6b4A95UFpC7OM0gQ8veQluN7b
"""

print("Phan Kim Ngan")