# -*- coding: utf-8 -*-
"""Untitled1.ipynb

Automatically generated by Colab.

Original file is located at
    https://colab.research.google.com/drive/1AM9Lyh-UWGP_LoToFrMS_JgWlEZD9mks
"""

#nhap hai so tu ban phim
so1 = int(input("Nhap so thu nhat: "))
so2 = int(input("Nhap so thu hai:"))
#tinh tong
tong = so1 + so2
#hien thi
print("Tong hai so la:", tong)